{
 "title": "saad",
 "time": { "from": "2024-12-03T11:22:22.852Z", "to": "2024-12-03T13:21:49.147Z" },
 "refresh": "5s",
 "panels": [
  {
   "title": "maintenance flag",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT \"maintenance_flag\" FROM \"cleaned_sensor_data\""
    }
   ]
  },
  {
   "title": "Oil Temperature",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT \"Oil_temperature\" FROM \"cleaned_sensor_data\"\n\n"
    }
   ]
  },
  {
   "title": "Train Pose",
   "type": "geomap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Motor current",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT \"Motor_current\" FROM \"cleaned_sensor_data\"\n\n"
    },
    {}
   ]
  },
  {
   "title": "DV Pressure",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "pressurebar" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT \"DV_pressure\" FROM \"cleaned_sensor_data\"\n\n\n\n"
    }
   ]
  },
  {
   "title": "Reservoirs",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "pressurebar" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT \"Reservoirs\" FROM \"cleaned_sensor_data\"\n\n"
    }
   ]
  },
  {
   "title": "LPS",
   "type": "bargauge",
   "description": "if LPS = 1  the pressure has droped",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT \"LPS\" FROM \"cleaned_sensor_data\""
    }
   ]
  },
  {
   "title": "DV Pressure",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "pressurebar" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT \"DV_pressure\" FROM \"cleaned_sensor_data\"\n\n"
    }
   ]
  },
  {
   "title": "Pneumatic panel TP3",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "pressurebar" } },
   "targets": [
    {
     "query": "SELECT \"TP3\" FROM \"cleaned_sensor_data\"\n\n"
    }
   ]
  }
 ]
}