{
 "title": "train1",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "maintenance flag for train1",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT \"maintenance_flag\" FROM \"cleaned_sensor_data\" \n"
    }
   ]
  },
  {
   "title": "Oil Temperature for train1",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT \"Oil_temperature\" FROM \"cleaned_sensor_data\" WHERE \"train_id\" = 'train1'\n\n\n"
    }
   ]
  },
  {
   "title": "Train 1 Pose",
   "type": "geomap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Motor current for train1",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT \"Motor_current\" FROM \"cleaned_sensor_data\" WHERE \"train_id\" = 'train1'\n\n"
    },
    {}
   ]
  },
  {
   "title": "DV Pressure of train1",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "pressurebar" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT \"DV_pressure\" FROM \"cleaned_sensor_data\" WHERE \"train_id\" = 'train1'\n\n\n\n"
    }
   ]
  },
  {
   "title": "Reservoirs of train1",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "pressurebar" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT \"Reservoirs\" FROM \"cleaned_sensor_data\" WHERE \"train_id\" = 'train1'\n \n\n"
    }
   ]
  },
  {
   "title": "LPS of train1",
   "type": "bargauge",
   "description": "if LPS = 1  the pressure has droped",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT \"LPS\" FROM \"cleaned_sensor_data\"  WHERE \"train_id\" = 'train1'"
    }
   ]
  },
  {
   "title": "DV Pressure of train1",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "pressurebar" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT \"DV_pressure\" FROM \"cleaned_sensor_data\"  WHERE \"train_id\" = 'train1'\n\n"
    }
   ]
  },
  {
   "title": "Pneumatic panel TP3 of train1",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "pressurebar" } },
   "targets": [
    {
     "query": "SELECT \"TP3\" FROM \"cleaned_sensor_data\" WHERE \"train_id\" = 'train1' \n\n\n"
    }
   ]
  }
 ]
}